"""
VOICE SHIELD AI — Model Evaluation & Benchmark Suite

IMPORTANT AUDIT NOTICE

This script contains TWO TYPES of evaluations:

A. UNIT/DEMO TESTS (lines 39-190+)
   - Uses SYNTHETIC MATHEMATICAL TONES generated by generate_synthetic_tone_wav()
   - NOT real human speech or real deepfake samples
   - These test the detector's ability to distinguish mathematical signal patterns
   - Metrics from these tests are for PROTOTYPING/UNIT TESTING only

B. REAL EVALUATION (if real samples exist in data/evaluation/)
   - Uses actual human voice recordings and real synthetic/deepfake samples
   - Requires labeled datasets (ASVspoof, VCC, etc.)
   - Only meaningful for real-world accuracy claims

DO NOT present synthetic tone results as real-world deepfake detection accuracy.
"""

import math
import sys
import time
import wave
from pathlib import Path
from typing import Any

# Ensure backend modules are on sys.path
backend_path = Path(__file__).resolve().parents[1] / "backend"
if str(backend_path) not in sys.path:
    sys.path.insert(0, str(backend_path))

from app.models.schemas import AcousticFeatures
from app.services.audio.preprocessing import extract_features, load_audio
from app.services.detection.deepfake import detect_synthetic_voice_detailed
from app.services.risk.scoring import calculate_risk_detailed
from app.services.speaker.verification import extract_speaker_embedding, verify_speaker_identity
from app.services.stt.social_engineering import analyze_context_detailed


def generate_synthetic_tone_wav(
    path: Path,
    carrier_freq: float = 220.0,
    duration_sec: float = 3.0,
    sample_rate: int = 16000,
    channels: int = 1,
    is_synthetic_artifact: bool = False,
    noise_level: float = 0.0,
) -> None:
    """
    Generates synthetic WAV audio files with controlled acoustic properties for benchmarking.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    num_samples = int(duration_sec * sample_rate)
    samples = []

    for i in range(num_samples):
        t = i / sample_rate
        if is_synthetic_artifact:
            # Neural vocoder artifacts:
            # 1. Robotic flat harmonic series with severe high-frequency phase noise (elevating ZCR > 0.32)
            val = math.sin(2 * math.pi * carrier_freq * t) * 0.03
            val += math.sin(2 * math.pi * (carrier_freq * 2) * t) * 0.02
            # Add high frequency phase noise (ZCR elevation and spectral contrast flattening)
            val += (math.sin(i * 12.345) * 0.015)
            # Severe dynamic range compression (dynamic range < 0.07)
            envelope = 0.95
        else:
            # Natural biological human voice simulation:
            # Fundamental + natural vibrato/jitter + biological formants (F1, F2, F3) + natural pauses
            f0 = carrier_freq + 4.0 * math.sin(2 * math.pi * 3.0 * t)  # Natural human pitch drift
            val = math.sin(2 * math.pi * f0 * t) * 0.4
            val += math.sin(2 * math.pi * (f0 * 2) * t) * 0.2
            val += math.sin(2 * math.pi * (f0 * 3) * t) * 0.1
            # Smooth biological envelope across call duration
            envelope = math.sin(math.pi * (t / duration_sec)) * (0.8 + 0.2 * math.sin(2 * math.pi * 1.5 * t))

        sample_float = val * envelope

        # Add ambient background noise if specified
        if noise_level > 0:
            sample_float += (math.sin(i * 997.0) * 0.5) * noise_level

        sample_int = int(max(-1.0, min(1.0, sample_float)) * 32767)
        samples.append(sample_int)

    with wave.open(str(path), "wb") as wav:
        wav.setnchannels(channels)
        wav.setsampwidth(2)
        wav.setframerate(sample_rate)
        if channels == 1:
            raw_bytes = b"".join(s.to_bytes(2, "little", signed=True) for s in samples)
        else:
            raw_bytes = b"".join(s.to_bytes(2, "little", signed=True) * channels for s in samples)
        wav.writeframes(raw_bytes)


def evaluate_deepfake_detector_unit_tests(eval_dir: Path) -> dict[str, Any]:
    """
    UNIT TESTS using synthetic mathematical tones.

    IMPORTANT: These are NOT real-world accuracy metrics.
    Tests detector's ability to distinguish synthetic signal patterns from "human-like" patterns.
    """
    print("\n" + "=" * 60)
    print("1. DEEPFAKE DETECTOR — UNIT TESTS (Synthetic Tones)")
    print("=" * 60)
    print("WARNING: These tests use generated mathematical signals, NOT real voice samples.")
    print("Results are for PROTOTYPING only, not real-world accuracy.\n")

    test_cases = [
        # (name, is_synthetic, carrier_freq, duration, sr, channels, noise)
        ("genuine_male_clean_16k", False, 120.0, 3.0, 16000, 1, 0.0),
        ("genuine_female_clean_16k", False, 220.0, 3.0, 16000, 1, 0.0),
        ("genuine_noisy_16k", False, 180.0, 3.0, 16000, 1, 0.08),
        ("genuine_short_0_8s", False, 150.0, 0.8, 16000, 1, 0.0),
        ("genuine_long_7s", False, 170.0, 7.0, 16000, 1, 0.0),
        ("genuine_stereo_44k", False, 160.0, 3.0, 44100, 2, 0.0),
        ("genuine_8k_telephony", False, 140.0, 3.0, 8000, 1, 0.0),
        ("synthetic_vocoder_16k", True, 180.0, 3.0, 16000, 1, 0.0),
        ("synthetic_high_artifact_16k", True, 240.0, 3.0, 16000, 1, 0.0),
        ("synthetic_noisy_16k", True, 190.0, 3.0, 16000, 1, 0.05),
        ("synthetic_short_1s", True, 210.0, 1.0, 16000, 1, 0.0),
        ("synthetic_stereo_48k", True, 200.0, 3.0, 48000, 2, 0.0),
    ]

    tp, fp, tn, fn = 0, 0, 0, 0
    latencies = []

    for name, is_synthetic, freq, dur, sr, ch, noise in test_cases:
        wav_path = eval_dir / f"{name}.wav"
        generate_synthetic_tone_wav(
            wav_path,
            carrier_freq=freq,
            duration_sec=dur,
            sample_rate=sr,
            channels=ch,
            is_synthetic_artifact=is_synthetic,
            noise_level=noise,
        )

        t0 = time.perf_counter()
        audio = load_audio(wav_path)
        features = extract_features(audio)
        result = detect_synthetic_voice_detailed(features, wav_path)
        latency = (time.perf_counter() - t0) * 1000.0
        latencies.append(latency)

        pred_synthetic = result.prediction in {"SYNTHETIC", "FAKE"}

        if is_synthetic and pred_synthetic:
            tp += 1
            status = "TP (True Positive)"
        elif not is_synthetic and not pred_synthetic:
            tn += 1
            status = "TN (True Negative)"
        elif not is_synthetic and pred_synthetic:
            fp += 1
            status = "FP (False Positive)"
        else:
            fn += 1
            status = "FN (False Negative)"

        print(f"  [{status}] {name:30} | Prob: {result.synthetic_probability:.2f} | Latency: {latency:.1f}ms")

    total = tp + fp + tn + fn
    accuracy = (tp + tn) / total if total > 0 else 0.0
    precision = tp / (tp + fp) if (tp + fp) > 0 else 0.0
    recall = tp / (tp + fn) if (tp + fn) > 0 else 0.0
    f1 = 2 * precision * recall / (precision + recall) if (precision + recall) > 0 else 0.0
    fpr = fp / (fp + tn) if (fp + tn) > 0 else 0.0
    fnr = fn / (fn + tp) if (fn + tp) > 0 else 0.0

    latencies.sort()
    mean_lat = sum(latencies) / len(latencies)
    p95_lat = latencies[int(len(latencies) * 0.95)]

    metrics = {
        "total_samples": total,
        "confusion_matrix": {"TP": tp, "FP": fp, "TN": tn, "FN": fn},
        "accuracy": round(accuracy, 4),
        "precision": round(precision, 4),
        "recall": round(recall, 4),
        "f1_score": round(f1, 4),
        "false_positive_rate": round(fpr, 4),
        "false_negative_rate": round(fnr, 4),
        "latency_mean_ms": round(mean_lat, 2),
        "latency_p95_ms": round(p95_lat, 2),
    }

    print("\nDeepfake Detection Unit Test Results:")
    print(f"  UNIT TEST ACCURACY: {metrics['accuracy']*100:.1f}% (on synthetic tones)")
    print(f"  These are NOT real-world deepfake detection metrics.\n")
    print(f"  Precision: {metrics['precision']*100:.1f}%")
    print(f"  Recall:    {metrics['recall']*100:.1f}%")
    print(f"  F1 Score:  {metrics['f1_score']:.4f}")
    print(f"  FPR:       {metrics['false_positive_rate']*100:.1f}%")
    print(f"  FNR:       {metrics['false_negative_rate']*100:.1f}%")
    print(f"  Avg Latency: {metrics['latency_mean_ms']}ms (p95: {metrics['latency_p95_ms']}ms)")

    return metrics


def evaluate_deepfake_detector_real(eval_dir: Path) -> dict[str, Any]:
    """
    REAL EVALUATION using actual human speech and deepfake samples.

    Requires: data/evaluation/real/ and data/evaluation/synthetic/ directories
    with real labeled audio files (e.g. from ASVspoof, VCC, WaveFake datasets).

    Supported audio formats: .wav, .flac, .mp3, .ogg, .m4a

    Returns structured metrics dict, or "no_real_samples" if data is unavailable.
    """
    real_dir = eval_dir / "real"
    synthetic_dir = eval_dir / "synthetic"

    print("\n" + "=" * 60)
    print("DEEPFAKE DETECTOR — REAL EVALUATION")
    print("=" * 60)

    if not real_dir.exists() or not synthetic_dir.exists():
        print("\nREAL EVALUATION DATA NOT AVAILABLE")
        print("   Required directories:")
        print(f"   - {real_dir}/")
        print(f"   - {synthetic_dir}/")
        print("\n   To perform real evaluation:")
        print("   1. Download ASVspoof, WaveFake, or similar labeled dataset")
        print("   2. Place bonafide (real human) samples in data/evaluation/real/")
        print("   3. Place spoofed/synthetic samples in data/evaluation/synthetic/")
        print("   4. Re-run this evaluation script")
        print("\n   NOTE: Current metrics are from UNIT TESTS only (synthetic tones).")
        print("         Real-world accuracy requires actual labeled voice data.")
        return {"status": "no_real_samples", "message": "Real evaluation data directories not found"}

    # Discover supported audio files
    SUPPORTED_EXTS = {".wav", ".flac", ".mp3", ".ogg", ".m4a", ".aac"}

    real_files = [
        f for f in real_dir.iterdir()
        if f.is_file() and f.suffix.lower() in SUPPORTED_EXTS
    ]
    synthetic_files = [
        f for f in synthetic_dir.iterdir()
        if f.is_file() and f.suffix.lower() in SUPPORTED_EXTS
    ]

    if not real_files and not synthetic_files:
        print("\nREAL EVALUATION DATA NOT AVAILABLE")
        print(f"   Directories exist but contain no supported audio files:")
        print(f"   - {real_dir}/ — {len(list(real_dir.iterdir()))} items (none are supported audio)")
        print(f"   - {synthetic_dir}/ — {len(list(synthetic_dir.iterdir()))} items (none are supported audio)")
        print(f"   Supported formats: {', '.join(sorted(SUPPORTED_EXTS))}")
        return {"status": "no_real_samples", "message": "No supported audio files found in evaluation directories"}

    total_real = len(real_files)
    total_synthetic = len(synthetic_files)
    print(f"\nFound {total_real} real (bonafide) samples in: {real_dir}")
    print(f"Found {total_synthetic} synthetic (spoof) samples in: {synthetic_dir}")
    print()

    tp, fp, tn, fn = 0, 0, 0, 0
    latencies = []
    per_file_results = []

    # Evaluate real (bonafide) files — expected: REAL prediction
    print("Evaluating real (bonafide) samples...")
    for audio_path in real_files:
        t0 = time.perf_counter()
        try:
            audio = load_audio(audio_path)
            features = extract_features(audio)
            result = detect_synthetic_voice_detailed(features, audio_path)
            latency = (time.perf_counter() - t0) * 1000.0
            latencies.append(latency)

            pred_synthetic = result.prediction in {"SYNTHETIC", "FAKE"}
            is_fp = pred_synthetic  # real file predicted as synthetic = false positive

            if is_fp:
                fp += 1
                status_tag = "FP"
            else:
                tn += 1
                status_tag = "TN"

            print(f"  [{status_tag}] {audio_path.name:40} | Prob: {result.synthetic_probability:.3f} | Model: {result.model_type} | Latency: {latency:.0f}ms")
            per_file_results.append({
                "file": audio_path.name,
                "true_label": "real",
                "predicted": "synthetic" if pred_synthetic else "real",
                "synthetic_probability": result.synthetic_probability,
                "model_type": result.model_type,
                "model_name": result.model_name,
                "inference_time_ms": round(latency, 2),
                "correct": not is_fp,
            })
        except Exception as exc:
            latency = (time.perf_counter() - t0) * 1000.0
            print(f"  [ERR] {audio_path.name:40} | Error: {exc}")
            per_file_results.append({
                "file": audio_path.name,
                "true_label": "real",
                "predicted": "error",
                "synthetic_probability": None,
                "model_type": "error",
                "model_name": "error",
                "inference_time_ms": round(latency, 2),
                "correct": False,
                "error": str(exc),
            })

    print()
    print("Evaluating synthetic (spoof/deepfake) samples...")
    for audio_path in synthetic_files:
        t0 = time.perf_counter()
        try:
            audio = load_audio(audio_path)
            features = extract_features(audio)
            result = detect_synthetic_voice_detailed(features, audio_path)
            latency = (time.perf_counter() - t0) * 1000.0
            latencies.append(latency)

            pred_synthetic = result.prediction in {"SYNTHETIC", "FAKE"}
            is_tp = pred_synthetic  # synthetic file predicted as synthetic = true positive

            if is_tp:
                tp += 1
                status_tag = "TP"
            else:
                fn += 1
                status_tag = "FN"

            print(f"  [{status_tag}] {audio_path.name:40} | Prob: {result.synthetic_probability:.3f} | Model: {result.model_type} | Latency: {latency:.0f}ms")
            per_file_results.append({
                "file": audio_path.name,
                "true_label": "synthetic",
                "predicted": "synthetic" if pred_synthetic else "real",
                "synthetic_probability": result.synthetic_probability,
                "model_type": result.model_type,
                "model_name": result.model_name,
                "inference_time_ms": round(latency, 2),
                "correct": is_tp,
            })
        except Exception as exc:
            latency = (time.perf_counter() - t0) * 1000.0
            print(f"  [ERR] {audio_path.name:40} | Error: {exc}")
            per_file_results.append({
                "file": audio_path.name,
                "true_label": "synthetic",
                "predicted": "error",
                "synthetic_probability": None,
                "model_type": "error",
                "model_name": "error",
                "inference_time_ms": round(latency, 2),
                "correct": False,
                "error": str(exc),
            })

    # Calculate metrics
    total = tp + fp + tn + fn
    accuracy = (tp + tn) / total if total > 0 else 0.0
    precision = tp / (tp + fp) if (tp + fp) > 0 else 0.0
    recall = tp / (tp + fn) if (tp + fn) > 0 else 0.0
    f1 = 2 * precision * recall / (precision + recall) if (precision + recall) > 0 else 0.0
    fpr = fp / (fp + tn) if (fp + tn) > 0 else 0.0
    fnr = fn / (fn + tp) if (fn + tp) > 0 else 0.0

    mean_lat = sum(latencies) / len(latencies) if latencies else 0.0
    latencies_sorted = sorted(latencies)
    p95_lat = latencies_sorted[int(len(latencies_sorted) * 0.95)] if latencies_sorted else 0.0

    metrics = {
        "status": "completed",
        "total_real_samples": total_real,
        "total_synthetic_samples": total_synthetic,
        "total_evaluated": total,
        "confusion_matrix": {"TP": tp, "FP": fp, "TN": tn, "FN": fn},
        "accuracy": round(accuracy, 4),
        "precision": round(precision, 4),
        "recall": round(recall, 4),
        "f1_score": round(f1, 4),
        "false_positive_rate": round(fpr, 4),
        "false_negative_rate": round(fnr, 4),
        "latency_mean_ms": round(mean_lat, 2),
        "latency_p95_ms": round(p95_lat, 2),
        "per_file_results": per_file_results,
    }

    print("\n" + "=" * 60)
    print("REAL EVALUATION RESULTS")
    print("=" * 60)
    print(f"  Total samples evaluated: {total} ({total_real} real + {total_synthetic} synthetic)")
    print(f"  Confusion Matrix: TP={tp} | FP={fp} | TN={tn} | FN={fn}")
    print(f"  Accuracy:  {accuracy * 100:.1f}%")
    print(f"  Precision: {precision * 100:.1f}%")
    print(f"  Recall:    {recall * 100:.1f}%")
    print(f"  F1 Score:  {f1:.4f}")
    print(f"  FPR:       {fpr * 100:.1f}% (real voices flagged as synthetic)")
    print(f"  FNR:       {fnr * 100:.1f}% (synthetic voices missed)")
    print(f"  Avg Latency: {mean_lat:.1f}ms (p95: {p95_lat:.1f}ms)")

    # Save results
    import csv
    results_dir = eval_dir.parent.parent / "evaluation" / "results"
    results_dir.mkdir(parents=True, exist_ok=True)

    json_path = results_dir / "real_evaluation_results.json"
    with open(json_path, "w", encoding="utf-8") as f:
        import json as json_module
        json_module.dump(metrics, f, indent=2)
    print(f"\n  Results saved to: {json_path}")

    csv_path = results_dir / "real_evaluation_per_file.csv"
    if per_file_results:
        with open(csv_path, "w", newline="", encoding="utf-8") as f:
            writer = csv.DictWriter(f, fieldnames=per_file_results[0].keys())
            writer.writeheader()
            writer.writerows(per_file_results)
        print(f"  Per-file CSV saved to: {csv_path}")

    return metrics



def evaluate_speaker_verification_unit_tests(eval_dir: Path) -> dict[str, Any]:
    """
    SPEAKER VERIFICATION UNIT TESTS using synthetic tones.

    IMPORTANT: These test the handcrafted spectral embedding's ability to distinguish
    different pitch frequencies, not real speaker recognition accuracy.
    """
    print("\n" + "=" * 60)
    print("2. SPEAKER VERIFICATION — UNIT TESTS (Synthetic Tones)")
    print("=" * 60)
    print("Tests handcrafted embedding baseline, NOT pretrained speaker model.\n")

    # Generate 3 distinct speaker voices
    spk1_ref = eval_dir / "spk1_reference.wav"
    spk1_test = eval_dir / "spk1_test_call.wav"
    spk2_ref = eval_dir / "spk2_impostor.wav"

    generate_synthetic_tone_wav(spk1_ref, carrier_freq=150.0, duration_sec=3.0)
    generate_synthetic_tone_wav(spk1_test, carrier_freq=152.0, duration_sec=3.0)  # Same speaker, minor natural variance
    generate_synthetic_tone_wav(spk2_ref, carrier_freq=240.0, duration_sec=3.0)   # Impostor speaker

    emb_spk1_ref = extract_speaker_embedding(spk1_ref)
    emb_spk1_test = extract_speaker_embedding(spk1_test)
    emb_spk2_ref = extract_speaker_embedding(spk2_ref)

    match_res = verify_speaker_identity(emb_spk1_test, emb_spk1_ref, threshold=0.70)
    impostor_res = verify_speaker_identity(emb_spk2_ref, emb_spk1_ref, threshold=0.70)

    print(f"  Same Speaker Comparison:     Match={match_res.speaker_match} | Sim={match_res.similarity:.3f} | Score={match_res.speaker_match_score}/100")
    print(f"  Impostor Speaker Comparison: Match={impostor_res.speaker_match} | Sim={impostor_res.similarity:.3f} | Score={impostor_res.speaker_match_score}/100")

    is_success = match_res.speaker_match and (not impostor_res.speaker_match)
    print("\nNOTE: These results are from synthetic tones with different pitch frequencies.")
    print("Real speaker verification requires pretrained embeddings (x-vector, ECAPA-TDNN).\n")

    return {
        "same_speaker_similarity": match_res.similarity,
        "impostor_similarity": impostor_res.similarity,
        "biometric_isolation_verified": is_success,
    }


def evaluate_multilingual_context_unit_tests() -> dict[str, Any]:
    """
    MULTILINGUAL SOCIAL ENGINEERING DETECTION UNIT TESTS.

    Tests keyword/regex pattern matching on text transcripts.
    These are deterministic unit tests, not real NLP accuracy metrics.
    """
    print("\n" + "=" * 60)
    print("3. MULTILINGUAL CONTEXT DETECTION — UNIT TESTS")
    print("=" * 60)
    print("Tests keyword/pattern detection, not real NLP classification.\n")

    test_transcripts = [
        ("en_clean_routine", "Hello team, let's sync up for the project status meeting.", False),
        ("en_urgent_wire", "This is urgent. Transfer funds to this account number immediately.", True),
        ("en_otp_scam", "Share the OTP right now and keep this strictly confidential.", True),
        ("hi_devanagari_fraud", "तुरंत पैसे ट्रांसफर करो और अपना ओटीपी किसी को मत बताना", True),
        ("hinglish_extortion", "Turant paise bhejo khate me, police warrant issue ho gaya hai digital arrest hoga", True),
        ("te_roman_fraud", "Ventane dabbu pampandi evariki cheppavaddhu rahasyam", True),
        ("ta_roman_fraud", "Udane panam anuppu yaarukkum sollaatheenga ragasiyam", True),
        ("casual_greeting", "Good morning Ajay, see you at lunch today.", False),
    ]

    tp, fp, tn, fn = 0, 0, 0, 0
    for name, text, is_threat in test_transcripts:
        res = analyze_context_detailed(text)
        pred_threat = res["context_risk"] >= 0.25

        if is_threat and pred_threat:
            tp += 1
            tag = "TP"
        elif not is_threat and not pred_threat:
            tn += 1
            tag = "TN"
        elif not is_threat and pred_threat:
            fp += 1
            tag = "FP"
        else:
            fn += 1
            tag = "FN"

        print(f"  [{tag}] {name:22} | Lang: {res['language']:20} | Risk: {res['context_risk_score']:3}/100 ({res['risk_level']})")

    accuracy = (tp + tn) / (tp + fp + tn + fn)
    print(f"\nMultilingual Context Unit Test Accuracy: {accuracy*100:.1f}% ({tp+tn}/{tp+fp+tn+fn} correct)")
    print("NOTE: These are PATTERN MATCHING unit tests, not real NLP accuracy.\n")
    return {"accuracy": round(accuracy, 4), "total_cases": len(test_transcripts)}


if __name__ == "__main__":
    temp_eval_dir = Path(__file__).resolve().parents[1] / "data" / "temp" / "eval_benchmarks"
    temp_eval_dir.mkdir(parents=True, exist_ok=True)

    # Real evaluation data directory (user must populate with labeled audio)
    real_eval_dir = Path(__file__).resolve().parents[1] / "data" / "evaluation"

    print("\n" + "=" * 60)
    print("VOICE SHIELD AI - EVALUATION SUITE")
    print("=" * 60)
    print("This suite runs TWO types of evaluation:")
    print("  A. UNIT TESTS  — synthetic tone signals (always runs)")
    print("  B. REAL EVAL   — actual labeled audio files (requires data in data/evaluation/)")
    print("See scripts/evaluate_models.py header for full documentation.\n")

    # ─── A. UNIT TESTS (always run) ────────────────────────────────
    print("\n" + "=" * 60)
    print("SECTION A: UNIT TESTS (Synthetic Tones)")
    print("=" * 60)
    print("WARNING: These test the detector on mathematical signals,")
    print("NOT real voice recordings. Do NOT cite as real-world accuracy.\n")

    df_unit_metrics = evaluate_deepfake_detector_unit_tests(temp_eval_dir)
    spk_metrics = evaluate_speaker_verification_unit_tests(temp_eval_dir)
    ctx_metrics = evaluate_multilingual_context_unit_tests()

    # ─── B. REAL EVALUATION (requires labeled data) ────────────────
    print("\n" + "=" * 60)
    print("SECTION B: REAL EVALUATION (Actual Audio Files)")
    print("=" * 60)

    df_real_metrics = evaluate_deepfake_detector_real(real_eval_dir)

    # ─── FINAL SUMMARY ─────────────────────────────────────────────
    print("\n" + "=" * 60)
    print("VOICE SHIELD AI - EVALUATION COMPLETE")
    print("=" * 60)
    print("\nSECTION A — UNIT TEST SUMMARY (synthetic tones):")
    print(f"  Deepfake detection unit test accuracy: {df_unit_metrics['accuracy']*100:.1f}% (on synthetic tones ONLY)")
    print(f"  Speaker verification biometric isolation: {spk_metrics['biometric_isolation_verified']}")
    print(f"  Multilingual context unit test accuracy: {ctx_metrics['accuracy']*100:.1f}% (pattern matching only)")
    print()
    print("SECTION B — REAL EVALUATION SUMMARY:")
    if df_real_metrics.get("status") == "completed":
        print(f"  Real evaluation COMPLETED on {df_real_metrics['total_evaluated']} samples")
        print(f"  Accuracy:  {df_real_metrics['accuracy']*100:.1f}%")
        print(f"  F1 Score:  {df_real_metrics['f1_score']:.4f}")
        print(f"  Results saved to: data/evaluation/results/")
    else:
        print(f"  Status: {df_real_metrics.get('status', 'unknown')}")
        print(f"  Message: {df_real_metrics.get('message', '')}")
        print(f"  -> To enable real evaluation, place labeled audio in:")
        print(f"    data/evaluation/real/      (bonafide human speech)")
        print(f"    data/evaluation/synthetic/ (AI-generated/spoof speech)")
    print("=" * 60)

